services:
  postgres:
    image: postgres:17-alpine3.19
    container_name: postgres_benchmark
    environment:
      POSTGRES_DB: laravel_benchmark
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - benchmark_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U laravel -d laravel_benchmark"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine3.19
    container_name: redis_benchmark
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - benchmark_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  php-fpm:
    build:
      context: ./docker/php-fpm
      dockerfile: Dockerfile
    image: project-2-php-fpm
    container_name: php_fpm_benchmark
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8002:80"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - benchmark_network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_benchmark
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  swoole:
    build:
      context: ./docker/swoole
      dockerfile: Dockerfile
    image: project-2-swoole
    container_name: swoole_benchmark
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8001:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - benchmark_network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_benchmark
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frankenphp:
    build:
      context: ./docker/frankenphp
      dockerfile: Dockerfile
    image: project-2-frankenphp
    container_name: frankenphp_benchmark
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "8003:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - benchmark_network
    environment:
      DB_CONNECTION: pgsql
      DB_HOST: postgres
      DB_PORT: 5432
      DB_DATABASE: laravel_benchmark
      DB_USERNAME: laravel
      DB_PASSWORD: secret
      REDIS_HOST: redis
      REDIS_PORT: 6379
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data:

networks:
  benchmark_network:
    driver: bridge
